default: &default
  dispatchers:
    - polling_interval: 0.5
      batch_size: 100
  workers:
    # High priority workers for import processing (CPU intensive)
    - queues: "import_processing"
      threads: 2
      processes: <%= ENV.fetch("IMPORT_WORKERS", 2) %>
      polling_interval: 0.1
    # Medium priority workers for post-processing (moderate resources)
    - queues: "post_processing"
      threads: 3
      processes: <%= ENV.fetch("POST_PROCESSING_WORKERS", 2) %>
      polling_interval: 0.2
    # Low priority workers for background tasks (lightweight)
    - queues: "low_priority"
      threads: 2
      processes: <%= ENV.fetch("LOW_PRIORITY_WORKERS", 1) %>
      polling_interval: 0.5
    # Default queue for other jobs
    - queues: "default"
      threads: 2
      processes: <%= ENV.fetch("DEFAULT_WORKERS", 1) %>
      polling_interval: 0.3

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
